### ISSUE TITLE
[Plan] 简易自定义 GUI

### ISSUE THREAD

**Issue by katorly** [katorlys/StarlinUtils#26]
### Suggestion

```[tasklist]
### Tasks
- [ ] 普通 GUI 菜单（具体待规划）
- [ ] 翻页 GUI 菜单（具体待规划）
- [ ] 交互式 GUI 菜单，例如可放入物品等（具体待规划）
``` 

[Invero](https://github.com/Arasple/Invero) 已经够牛了，我觉得这个计划可以不要

### Reason

略
